version: 0.1

log:
  level: debug
  fields:
    service: registry

proxy:
  remoteurl: https://registry-1.docker.io
  # username: runalsh
  # password: password
  ttl: 168h

validation:
  disabled: false
  
prometheus:
  enabled: true
  path: /metrics
  
http:
    addr: 0.0.0.0:5000
    debug:
        addr: 0.0.0.0:5001
        prometheus:
            enabled: true
            path: /metrics
    net: tcp
    headers:
        X-Content-Type-Options: [nosniff]
        Access-Control-Allow-Origin: ['*']
        Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
        Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
        Access-Control-Expose-Headers: ['Docker-Content-Digest']
        Access-Control-Max-Age: [1728000]
        Access-Control-Allow-Credentials: [true]
    tls:
        certificate: /etc/ssl/fullchain.pem
        key: /etc/ssl/privkey.pem
    # clientcas:
      # - /path/to/ca.pem
      # - /path/to/another/ca.pem
    # letsencrypt:
      # # cachefile: /path/to/cache-file
      # # email: emailused@letsencrypt.com
      # # hosts: [myregistryaddress.org]
      # # directoryurl: https://acme-v02.api.letsencrypt.org/directory    
# health:
  # storagedriver:
    # enabled: true
    # interval: 10s
    # threshold: 3

storage:
  cache:
    blobdescriptor: inmemory
    blobdescriptorsize: 10000  
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  # tag:
    # concurrencylimit: 8
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
  delete:
    enabled: true         

notifications:
    events:
        includereferences: true
    endpoints:
        - name: local-8082
          url: http://localhost:5003/callback
          headers:
             Authorization: [Bearer <an example token>]
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true
        - name: local-8083
          url: http://localhost:8083/callback
          timeout: 1s
          threshold: 10
          backoff: 1s
          disabled: true

auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/auth.htpasswd