version: '3.3'
services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    networks:
        registry:
    ports:
      - 5000:5000
    environment:
      - 'REGISTRY_STORAGE_DELETE_ENABLED=true'
      - TZ=Europe/Moscow
    volumes:
      - ./registry_data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml:ro
      - /etc/ssl/fullchain.pem:/etc/ssl/fullchain.pem:ro
      - /etc/ssl/privkey.pem:/etc/ssl/privkey.pem:ro
      - ./auth.htpasswd:/etc/docker/registry/auth.htpasswd:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.docker-mirror.loadbalancer.server.port=5000"
      - "traefik.http.routers.docker-mirror.service=docker-mirror"
      - "traefik.http.routers.docker-mirror.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.docker-mirror.entrypoints=https"
      - "traefik.http.routers.docker-mirror.tls=true"
      - "traefik.http.routers.docker-mirror.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.docker-mirror-rewrite.replacepathregex.regex=^/v2/([^/]+)/((manifests|blobs)/.+)"
      - "traefik.http.middlewares.docker-mirror-rewrite.replacepathregex.replacement=/v2/library/$$1/$$2"
      - "traefik.http.routers.docker-mirror.middlewares=docker-mirror-rewrite"  
  
  traefik:
    image: traefik:3.0
    container_name: front
    restart: unless-stopped
    networks:
        registry:
    ports:
      - 80:80
      - 443:443
      # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./certs-traefik:/etc/traefik/acme
    depends_on:
      - registry

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:main
    restart: always
    networks:
        registry:
    ports:
      - 5001:443
    environment:
      - TZ=Europe/Moscow
      - SINGLE_REGISTRY=false
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://registry:5000
      # - DEFAULT_REGISTRIES=http://localhost:5002,http://localhost:5001 
      - DEFAULT_REGISTRIES=https://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
      - REGISTRY_ALLOW_DELETE=true
    volumes:
      - /etc/ssl/fullchain.pem:/etc/ssl/fullchain.pem
      - /etc/ssl/privkey.pem:/etc/ssl/privkey.pem
      - ./auth.htpasswd:/etc/docker/registry/auth.htpasswd
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.docker-mirror.loadbalancer.server.port=5001"
      - "traefik.http.routers.docker-mirror.service=docker-mirror"
      - "traefik.http.routers.docker-mirror.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.docker-mirror.entrypoints=https"
      - "traefik.http.routers.docker-mirror.tls=true"
      - "traefik.http.routers.docker-mirror.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.docker-mirror-strip.stripprefix.prefixes=/ui"
      - "traefik.http.routers.docker-mirror.middlewares=docker-mirror-rewrite"
    depends_on:
      - registry
    
networks:
  registry:
  
# volumes:
  # registry_data:
    # driver: local 
